### ISSUE TITLE
2 High security issues

### ISSUE THREAD

**Issue by daveta** [techno-express/node-7z#10]
There appears to be 2 high-security errors using `npm audit`. 
These appear to be stemming from `node-wget`.  Any chance this package could be swapped out?

**Comment by techno-express** [comment]
Sure, but i haven't looked into anything else since creating feature that does the same thing simply. 

If you have solution submit PR. might be a little while before I do.

**Comment by techno-express** [comment]
it seems _`node-wget`_ using version of **`request`** that has that issue. It seems to be known problem. 

I might just fork and update.

**Comment by daveta** [comment]
Here are some PR's for the fixes..

https://github.com/techno-express/node-unpack-all/pull/1
https://github.com/techno-express/node-7z/pull/11

Let me know if you have any issues!

**Comment by techno-express** [comment]
Wow, i wasn't even watching that package, got no notification. That too can be replaced here it seems.

**Comment by techno-express** [comment]
I have forked `node-wget` and updated, issue not present now. i try keeping dependencies low or to none.
