### ISSUE TITLE
Help extract a single file!

### ISSUE THREAD

**Issue by wachidmudi** [techno-express/node-7z#3]
I'm really desperate, how can i extract a single file from archive? For example say we have the following files in the folder, each archive contains what's in the curly braces:
```
a.7z {folder{1.txt, 2.txt, 3.txt}}
b.7z {folder2{4.txt, 5.txt, 6.txt}}
c.7z {7.txt, 8.txt, 9.txt}
```
So running the script will result in having the following extracted (those are folders):
```
a{folder{1.txt}}
b{folder2{4.txt}}
c{7.txt}
```
Or files only, without folders
```
a{1.txt}
b{4.txt}
c{7.txt}
```
Is this possible?

**Comment by techno-express** [comment]
Yes, read over these commands https://sevenzip.osdn.jp/chm/cmdline/commands/index.htm
you need **7z x** https://sevenzip.osdn.jp/chm/cmdline/commands/extract.htm

**Comment by wachidmudi** [comment]
Thanks for your response. This is my code:
```
const Zip = require('node-7z-forall');
const myTask = new Zip();

const destination = 'output';
const zipFile = 'zip/files.zip';

myTask.extract(zipFile, destination, {
  r: true,
  raw: [ '-i!*.txt' ]
})
.progress(files => {
  console.log(files);
})
.then(() => console.log('Extracting done!'))
.catch((err) => console.log(err));
```
It did extract all files with .txt extension, but how can i extract the specific index of the txt file, let say i wanna the first one only! Can i?
I did try to `console.log(files)` on progress, but it return `undefined`.

**Comment by techno-express** [comment]
If you haven't figured it out, you will need to specific just that one file then.

**Comment by rishighan** [comment]
I know I am super late to answering this, but for a similar use case of extracting a single file and/or _cherry-picking_ files, you can use the `raw` key, which takes in an array of filename strings, like so:

```typescript
import { extract } from "node-7z-forall";

const extractionTargets = ["file1.jpg", "info.xml"];
await extract(path.resolve(filePath), targetDirectory, {
    r: true,
    raw: [...extractionTargets],
});
```
