### ISSUE TITLE
Deprecated repository of 7z file on MacOS 

### ISSUE THREAD

**Issue by MCFreddie777** [techno-express/node-7z#4]
The repository https://github.com/rudix-mac/pkg no longer exists and therefore 
https://raw.githubusercontent.com/rudix-mac/pkg/master/p7zip-16.02.pkg returns 404.

**Comment by MCFreddie777** [comment]
Also, https://raw.githubusercontent.com/rudix-mac/packages no longer uses versioning, therefore /packages/{{macOsVersion e.g. 10.11}} no longer exists. 

There's only one package https://raw.githubusercontent.com/rudix-mac/packages/master/p7zip-16.02.pkg , but I'm unable to test, whether it works on macOS <10.11.

**Comment by techno-express** [comment]
Thanks, i haven't been keeping up on insuring everything is current. 

Yes, It seems **rudix-mac** have switched things around. I will further look into creating a new build or unless you can do PR.

**Comment by MCFreddie777** [comment]
Well I was thinking about making the new PR to this repo but I can't find any suitable source for macOS 10.6 - 10.9. 

Couldn't we simply deprecate the binaries for the older systems and use single source as you do in windows & linux `getDataForPlatform()` ? 

If you agree I can create a PR in a short time.

**Comment by techno-express** [comment]
The PR would be fine, since no CI build system can really test for macOS 10.6 to 10.9 nowadays, and I don't have those systems setup to test on either.
