### ISSUE TITLE
Windows's directory separator \ isn't being replaced with / past the first level of directories

### ISSUE THREAD

**Issue by oskarlh** [techno-express/node-7z#7]
Create a zip file with multiple levels of directories. Use `list`. You would expect its `progress`'s `entries[].name` to contain
`folder0/folder1/file.txt`
but on Windows it contains
`folder0/folder1\file.txt`
See the backslash?

**Why this happens**
In several places throughout the code you'll find
`.replace(path.sep, '/')`
The person who wrote that expected `.replace` to replace all instances of `path.sep`, but that's not how `.replace` works. We could use something like `.replace(/\\/g, '/')` (though it would need to dynamically create a RegExp based on `path.sep` and get the escaping right) or the more modern `.replaceAll(path.sep, '/')` or we could call `.replace(path.sep, '/')` in a loop.

I created a failing test for `list`. See PR https://github.com/techno-express/node-7z/pull/6 . This bug likely also affects functions other than `list`.

**Comment by techno-express** [comment]
Whatever fix{PR) you come up with would be fine. Haven't used the package in a while. So i didn't notice the errors it now creates. 

I think the Appveyor build process needs to be checked, I think they changed some things around that could be causing issues too.

I use GitHub Actions for most things now, haven't gotten around to switch this package over.

**Comment by oskarlh** [comment]
> I think the Appveyor build process needs to be checked, I think they changed some things around that could be causing issues too.
That's quite possible, but the error message seems to be caused by the new test failing, as it should.

I'll write a fix and update the PR

**Comment by oskarlh** [comment]
Done :)

**Comment by oskarlh** [comment]
Done. Codeclimate is complaining about an unrelated code quality issue. I am sure it can be ignored for now

**Comment by techno-express** [comment]
Done, I published the updated version to npm.
